apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: exchange-backend-prd
  source:
    repoURL: 'https://github.com/NeorCloud/arvan-exchange-apps.git'
    path: pgo
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: exchange-backend-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - SelfHeal=true