{{ if .Values.logstash.enabled }}
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: {{ .Values.logstash.name }}
spec:
  count: 1
  elasticsearchRefs:
  - name: {{ .Values.logstash.elasticsearchRef.name }}
    clusterName: {{ .Values.logstash.elasticsearchRef.clusterName }}
  version: {{ .Values.logstash.version }}
  pipelines:
  {{- range .Values.logstash.pipelines }}
  - pipeline.id: {{ .id }}
    config.string: {{ .config | toYaml | nindent 4 }}
  {{- end }}
  services:
    {{ toYaml .Values.logstash.services | nindent 4 }}
  volumeClaimTemplates:
  - metadata:
      name: logstash-data # Do not change this name unless you set up a volume mount for the data path.
    spec:
      accessModes: {{ toYaml .Values.logstash.storage.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.logstash.storage.size }}
      storageClassName: {{ .Values.logstash.storage.storageClassName }}
{{ end }}